version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000mcoin
- name: bob
  coins:
  - 10000token
  - 100000000mcoin
faucet:
  name: faucet
  coins:
  - 5token
  - 100000mcoin
  host: 0.0.0.0:4500
genesis:
  chain_id: mycosmosblockchain
validators:
- name: alice
  bonded: 100000000mcoin
  app:
    api:
      address: :1317
    grpc:
      address: :9090
    grpc-web:
      address: :9091
  config:
    p2p:
      laddr: :26656
    rpc:
      laddr: :26657
      pprof_laddr: :6060
  home: $HOME/.mycosmosblockchain
init:
  home: $HOME/.mycosmosblockchain
  client:
    keyring-backend: test
