version: 1
build:
  proto:
    path: proto
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000mcoin
- name: bob
  coins:
  - 10000token
  - 100000000mcoin
faucet:
  name: faucet
  coins:
  - 5token
  - 100000mcoin
  host: 0.0.0.0:4500
genesis:
  chain_id: mycosmosblockchain
validators:
- name: alice
  bonded: 100000000mcoin
